### ISSUE TITLE
Request : Update readme with windows versions

### ISSUE THREAD

**Issue by iNgeon** [spdermn02/TouchPortal_Discord_Plugin#102]
Please can you update the readme and explain the difference between these versions : 
What is the versions.
1. Standard windows version
2. Windows Canary version
3. Windows PTB

**Comment by gitagogaming** [comment]
Thanks Ingeon, we have gone ahead and added a readme to help future users decide what version they might want to utilize.  

To answer your issue here directly as well.. generally speaking I would suggest the 'standard version' unless you reaaaaly want early access to certain discord features..

The new readme can be found in the installation section where I also included a video/gif as well 
https://github.com/spdermn02/TouchPortal_Discord_Plugin/blob/master/README.md#installation-and-configuration
