### ISSUE TITLE
Discord 0Auth2

### ISSUE THREAD

**Issue by MrJoinGamingYT** [spdermn02/TouchPortal_Discord_Plugin#29]
For me, it does not show the window, to accept the plugin integration to work with my account. I did restart the plugin, and everything i could do, but it still did not show up. I am very interested in using the plugin, and would love to hear, how we can solve the issue. Hoping for your answer, and have a good day!

-Mr_Join

**Comment by NoahNxT** [comment]
Any solution? Same issue over here...

**Comment by MrJoinGamingYT** [comment]
Im still waiting...

**Comment by spdermn02** [comment]
I apologize, I swear I didn't get a notification about this. 

There are a few possibilities
1) the process watcher can't locate the correct discord so make sure you downloaded the appropriate .tpp most of the time the base TPDiscord.tpp will work
2) if that doesn't work, try exiting both discord and touch portal from the system tray and then start discord wait for it to come up and start touch portal
3) if that doesn't work, go to the plugin settings and set "Skip Process watcher" to "Yes" and click save, then go back to the settings and stop and start the plug-in
4) if either discord or touch portal are running as admin, then they both need to be running as admin
5) otherwise jump into the Official Touch Portal Discord, and tag me in #discord plug-in channel and I'll help you there when I can. 

Again I apologize that I didn't respond sooner.

**Comment by MrJoinGamingYT** [comment]
its fine, Better something late, than nothing!

**Comment by MrJoinGamingYT** [comment]
whats your discord?

**Comment by spdermn02** [comment]
Touch Portal - https://discord.gg/MgxQb8r

**Comment by JoshuaMunoz** [comment]
Did you copy and paste the link generated when you picked scopes? That's how you get the window to pop up now. Same with adding bots.

**Comment by ReaperKills87** [comment]
Hello,

I was having the same issue, no authentication popup window.

Step 4:  if either discord or touch portal are running as admin, then they both need to be running as admin

Fixed my issue.
