### ISSUE TITLE
Can't connect to discord...

### ISSUE THREAD

**Issue by Isaac-Chow** [spdermn02/TouchPortal_Discord_Plugin#54]
the auth popup does not appear in discord. if you need pics feel free to ask

**Comment by spdermn02** [comment]
Hey, sorry I missed this yesterday. 

1) do a full shutdown of Touch Portal and discord from the system tray icon. start discord, once it's up, start touch portal. See if anything changes

2) turn on `include plug-in logs` on the Logs tab of Touch Portal and then send here your log.txt from %APPDATA%\TouchPortal. 

Thanks.

**Comment by Isaac-Chow** [comment]
Thanks, it works!

I am also interested in the open hardware monitor version 6,
it says that version 6 is unstable and might not work.
I tried it, and there is no actions added so I just use version 5 for now.

Will version 6 be complete soon?
I would love to use it!

Keep up your great work!

**Comment by spdermn02** [comment]
The v6 version should work. There shouldn't be any actions. Maybe events in v5, but v6 I think I deprecated them because they aren't really useful since the "when plugin state changes" event is already present. 

I'm actually working on a complete rewrite in node.JS that also dynamically creates states for all possible sensors. So no more limitation on what sensor data is available. But currently I was planning on abandoning the graphs/dials because my dynamic-icons plugin can now handle those so it would just be easier to not worry about the images in the ohm plugin. 

But again the v6 should work... just I haven't had a lot of time to do tons of testing. 

> Thanks, it works!
> 
> 
> 
> I am also interested in the open hardware monitor version 6,
> 
> it says that version 6 is unstable and might not work.
> 
> I tried it, and there is no actions added so I just use version 5 for now.
> 
> 
> 
> Will version 6 be complete soon?
> 
> I would love to use it!
> 
> 
> 
> Keep up your great work!
