### ISSUE TITLE
Latest TP app stuck on analyzing when installing the discord plugin.

### ISSUE THREAD

**Issue by apexiptv** [spdermn02/TouchPortal_Discord_Plugin#59]
I'm on desktop version 3.1 build 4 of the TP app. I downloaded the discord windows plugin tpp file and I've selected it in adding new plugin... The "IMPORTING PLUGIN..." window pops up and at the bottom it says "Analyzing the TPDiscord-Win.tpp.." this goes on forever and never stops. I've just installed the GoXLR plugin so I know I can install a plugin.

**Comment by apexiptv** [comment]
Yes I did. I installed the Elgato Key Light plugin directly after trying the TPDiscord-WIn.tpp file as well.

**Comment by apexiptv** [comment]
So the factor that isn't working is that file.
I even downloaded the file again to another partition... no luck

**Comment by spdermn02** [comment]
Okay I'll see what I can do to figure out what could cause it.

**Comment by spdermn02** [comment]
I just downloaded a fresh copy of TPDiscord-Win.tpp from my Releases page, and it loaded no problem. It will bring up a window about trusting the app, and if somehow that gets behind another window, that could be part of the issue? Otherwise I would need to see if your Log has anything in it.  Turn on `include plug-in logs` on the Logs tab of Touch Portal, and then reimport the plugin, once it's stuck, can you load your %APPDATA%\TouchPortal\log.txt here so I can review.

**Comment by spdermn02** [comment]
@apexiptv were you able to get this working? was this with the 4.3.1 version?
