### ISSUE TITLE
BUG: My plugin don't connect 

### ISSUE THREAD

**Issue by APCP12** [spdermn02/TouchPortal_Discord_Plugin#70]
I put all the things the plugin needs and my plugin don't connect

![image](https://user-images.githubusercontent.com/98698436/229170123-f30d2765-cd3e-4c52-b273-1c02571c75d5.png)

**Comment by spdermn02** [comment]
**Troubleshooting**

A few things could be an issue:
1) fully restart discord maybe something happened with the connection mechanism
2) the user you created the dev app with is not the same that is logged into the discord app
3) your redirect url isn’t correct on the dev app should be `http://localhost`
4) May need to uninstall and reinstall discord to fix its issues 


Otherwise I'll need you to turn on `include plug-in logs` on the Logs tab of touch portal, do a complete restart of touch portal, wait like 2-3 minutes and then send the log.txt from %APPDATA%\TouchPortal (win) or Documents/TouchPortal (Mac)

**Comment by APCP12** [comment]
One thing, I can use with Discord PTB Right?

**Comment by spdermn02** [comment]
Yes, honestly the only difference between the plugin files that reference PTB and Canary is what binary it looks for. I really should just include them all on windows and just have one to make it less confusing.  

But yes you should be able to use the PTB version. The only thing that could be a problem is if I messed up the .exe name in the config and thus it's looking for the wrong process before attempting to login.

**Comment by spdermn02** [comment]
If you are using the PTB version of the plugin, Then you need to use the PTB version of discord. If you want to use with regular discord you need to use the .tpp for just base Discord
