### ISSUE TITLE
How to reset a button after reading a DM?

### ISSUE THREAD

**Issue by ApophysX** [spdermn02/TouchPortal_Discord_Plugin#91]
No issue, just a question. I created a button in Touch Portal (${value:discord_DM_user}) when I get a DM the user is displayed, when I have read the message and there are no more new messages, the button should display something else. How do you do that?

**Comment by spdermn02** [comment]
Can you share a snapshot of your button? That way we see how you have it setup.

**Comment by ApophysX** [comment]
i Can :)
![Bild_2024-09-12_195050323](https://github.com/user-attachments/assets/5ba35fe5-53f4-4fad-9469-6770c96e2458)

**Comment by spdermn02** [comment]
Is that bottom one working? That would be the way to indicate the change happened

**Comment by gitagogaming** [comment]
> No issue, just a question. I created a button in Touch Portal (${value:discord_DM_user}) when I get a DM the user is displayed, when I have read the message and there are no more new messages, the button should display something else. How do you do that?

The event we get from discord only lets us know that one came in, it also not trigger if that DM is actively open (just like a normal DM sound on discord)  

So because we only know when we get a DM, we cant trigger a plugin side event that knows when a DM has been viewed or the notification is gone. 

So to 'work around' this we would have to create a custom value and use it to reset the text on the button when we need it to.  
Here is an example

![image](https://github.com/user-attachments/assets/7f20efd4-ba94-41a9-8fab-93cf23e30126)


I've also attached the button example, you wil have to rename it to a `tpb` file name as I had to change it to upload here directly.
[Discord-DM-Event-Example.zip](https://github.com/user-attachments/files/16988877/Discord-DM-Event-Example.zip)

**Comment by ApophysX** [comment]
> > No issue, just a question. I created a button in Touch Portal (${value:discord_DM_user}) when I get a DM the user is displayed, when I have read the message and there are no more new messages, the button should display something else. How do you do that?
> 
> The event we get from discord only lets us know that one came in, it also will not trigger if that DM is actively open (just like a normal DM sound on discord)
> 
> So because we only know when we get a DM, we cant trigger a plugin side event that knows when a DM has been viewed or the notification is gone.
> 
> So to 'work around' this we would have to create a custom value and use it to reset the text on the button when we need it to. Here is an example
> 
> ![image](https://private-user-images.githubusercontent.com/76603653/367157147-7f20efd4-ba94-41a9-8fab-93cf23e30126.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMjQ2MzUsIm5iZiI6MTcyNjIyNDMzNSwicGF0aCI6Ii83NjYwMzY1My8zNjcxNTcxNDctN2YyMGVmZDQtYmE5NC00MWE5LThmYWItOTNjZjIzZTMwMTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDEwNDUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2NGIzZDI5OGFhYzFjYzQwMmVjNTVmNGQzODQ1MWNhZDY0MTg1MDhiYjU1MmNmODBkYjE3MDBiN2E1NGYyNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0vcdspeAgdbAVFbcYaZltphR-xsA5iNiIdeC9hcNTBg)
> 
> I've also attached the button example, you wil have to rename it to a `tpb` file name as I had to change it to upload here directly. [Discord-DM-Event-Example.zip](https://github.com/user-attachments/files/16988877/Discord-DM-Event-Example.zip)

Okay and thank you very much, it works.
